image: "registry.gitlab.com/synsense/rockpool/test:latest"

stages:
    - build
    - test
    - coverage
    - deploy

before_script:
  - pip install torchvision -U
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install . --no-cache-dir
  - pip install -r docs/requirements.txt
  - export PYTHON_SITE_PACKAGES=$(python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')


dist_build:
  tags:
    - python
    - aiCTX
  stage: build
  only:
    refs:
      - master
  before_script:
    - pip install wheel
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist

pages:
  tags:
    - python
    - aiCTX
  stage: deploy
  only:
    refs:
      - master
  script:
    - python setup.py build_sphinx
    - mv docs/build/html/ public/
  artifacts:
    paths:
      - public

test coverage:
  tags:
    - python
    - aiCTX
  stage: coverage
  dependencies:
   - unittests
  script:
    - pip install pytest-cov
    - pytest --cov

test coverage deplop:
  tags:
    - python
    - aiCTX
  stage: deploy
  dependencies:
    - test coverage
  only:
    refs:
      - master
  script:
    - pip install pytest-cov
    - pytest --cov
    - coverage report
    - coverage xml
    - wget https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov

doc_tests:
  tags:
    - python
    - aiCTX
  stage: test
  script:
    - python setup.py build_sphinx

unittests:
  tags:
    - python
    - aiCTX
  stage: test
  script:
    - pytest

pypi_deploy:
  tags:
    - python
    - aiCTX
  stage: deploy
  only:
    refs:
      - master
    variables:
      - $TWINE_USERNAME == "sheiksadique"
  dependencies:
    - dist_build
  before_script:
    - pip install --upgrade twine
  script:
    - twine upload dist/*
